FROM quay.io/wildfly/wildfly:latest-jdk11

# Enable Jaeger
ENV JAEGER_SERVICE_NAME=jaeger
ENV JAEGER_AGENT_HOST=jaeger
ENV JAEGER_REPORTER_LOG_SPANS=false
ENV JAEGER_SAMPLER_TYPE=const
ENV JAEGER_SAMPLER_PARAM=0

COPY target/acmeair-bookingservice-java-5.0.war /opt/jboss/wildfly/standalone/deployments/

# Avoid annoying CDi INFO Message
RUN sed -i 's/<level name="INFO"/<level name="WARN"/' /opt/jboss/wildfly/standalone/configuration/standalone-microprofile.xml

USER 0
RUN chown jboss:0 /opt/jboss/wildfly/standalone/deployments/acmeair-bookingservice-java-5.0.war
USER jboss

ENV JAVA_OPTS="-Xms64m -Xmx1024m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -Dhttp.keepalive=true -Dhttp.maxConnections=100"

#ENV KEYSTORE_LOCATION=/opt/boss/wildfly/key.p12
#ENV MONGO_HOST=10.0.0.82
#ENV ACMEAIR_STACKAA_AUTH_URL=http://acmeair-nginx1/auth
#ENV ACMEAIR_STACKAA_CUSTOMER_URL=http://acmeair-nginx1/customer
#ENV ACMEAIR_STACKAA_FLIGHT_URL=http://acmeair-nginx1/flight


CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-c","standalone-microprofile.xml","-b", "0.0.0.0", "-bmanagement", "0.0.0.0","-Djboss.http.port=9080"]
