## Stage 1 : build with maven builder image with native capabilities
FROM quay.io/quarkus/ubi-quarkus-mandrel-builder-image:23.1-java21 AS build
COPY --chown=quarkus:quarkus mvnw /code/mvnw
COPY --chown=quarkus:quarkus .mvn /code/.mvn
COPY --chown=quarkus:quarkus pom.quarkus.xml /code/pom.xml
USER quarkus
WORKDIR /code
RUN ./mvnw -B org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline
COPY src /code/src
COPY src/main/java/com/acmeair/mongo/MongoProducer.java.quarkus.native /code/src/main/java/com/acmeair/mongo/MongoProducer.java
RUN ./mvnw package -Pnative -Dmaven.test.skip

## Stage 2 : create the docker final image
FROM quay.io/quarkus/quarkus-micro-image:2.0
WORKDIR /work/
COPY --from=build /code/target/*-runner /work/application

# set up permissions for user `1001`
RUN chmod 775 /work /work/application \
  && chown -R 1001 /work \
  && chmod -R "g+rwX" /work \
  && chown -R 1001:root /work

EXPOSE 9080
USER 1001

CMD ["./application", "-Xmx512m","-Dhttp.keepalive=true","-Dhttp.maxConnections=100","-Dquarkus.http.host=0.0.0.0","-Dquarkus.http.port=9080","-Djava.util.logging.manager=org.jboss.logmanager.LogManager"]
