security:
  providers:
    - mp-jwt-auth:
        atn-token:
        sign-token:
          outbound:
tracing:
    service: "helidon-service"
    log-spans: false
    sampler-param: 1
    sampler-type: const
