apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmeair-bookingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: acmeair-booking-deployment
  template:
    metadata:
      labels:
        name: acmeair-booking-deployment
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
    spec:
      containers:
      - name: acmeair-bookingservice-java
        image: acmeair-bookingservice-java:latest
        ports:
          - containerPort: 9080
          - containerPort: 9443
        imagePullPolicy: Always
        env:
        - name: USERNAME
          value: admin
        - name: PASSWORD
          value: password
        - name: MONGO_HOST
          value: acmeair-booking-db
        - name: ACMEAIR_STACKAA_AUTH_URL
          value: "http://acmeair-auth-service:9080/auth"
        - name: ACMEAIR_STACKAA_CUSTOMER_URL
          value: "http://acmeair-customer-service:9080/customer"
        - name: ACMEAIR_STACKAA_FLIGHT_URL
          value: "http://acmeair-flight-service:9080/flight"
        - name: JAEGER_AGENT_HOST
          value: jaeger-all-in-one-inmemory-agent
        - name: JAEGER_AGENT_PORT
          value: '6832'
        - name: JAEGER_ENDPOINT
          value: 'http://jaeger-all-in-one-inmemory-collector:14268/api/traces'
        - name: ACCESS_LOGGING_ENABLED
          value: 'false'
        - name: TRACE_SPEC
          value: '*=info'
        readinessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 20
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 120
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: acmeair-booking-service
spec:
  ports:
    - name: 9080-tcp
      protocol: TCP
      port: 9080
      targetPort: 9080
  selector:
    name: acmeair-booking-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: acmeair-secure-booking-service
spec:
  ports:
    - name: 9443-tcp
      protocol: TCP
      port: 9443
      targetPort: 9443
  selector:
    name: acmeair-booking-deployment
---
##### Booking Database  #####
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: acmeair-booking-db
  name: acmeair-booking-db
spec:
  ports:
  - name: "27017"
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: acmeair-booking-db
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: acmeair-booking-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: acmeair-booking-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: acmeair-booking-db
    spec:
      volumes:
        - name: acmeair-booking-db-1
          emptyDir: {}
        - name: acmeair-booking-db-2
          emptyDir: {}
      containers:
      - image: mongo
        name: acmeair-booking-db
        ports:
        - containerPort: 27017
          protocol: TCP
        resources: {}
        volumeMounts:
          - name: acmeair-booking-db-1
            mountPath: /data/configdb
          - name: acmeair-booking-db-2
            mountPath: /data/db
      restartPolicy: Always
status: {}
